#Mike Minheere 99067548

import time
def path1():
    print('je komt een verlaten dorp tegen, wat doe je?')
    verlatenDorp = input('huizen doorzoeken (1) of doorlopen? (2) ')
    if verlatenDorp == '1':
        time.sleep(2)
        print()
        print('je gaat de huizen doorzoeken en je vind niet veel.')
        time.sleep(2.5)
        print('in het laatste huis dat je doorzoekt vind je wel een mes!')
        time.sleep(2.5)
        print('je gaat verder door het bos lopen totdat er ineens een wolf voor je neus staat!')
        time.sleep(2.5)
        print('gelukkig heb jij een mes gevonden! je steekt de wolf in zijn poot.')
        time.sleep(2.5)
        print('de wolf rent weg en, voor nu, ben je veilig.')
        time.sleep(3)
        print('je loopt verder en op een gegeven moment kom je een weg tegen.')
        time.sleep(1)
        weg = input('ga je naar links (1) of rechts? (2) ')
        if weg == '1':
            time.sleep(1)
            print('je gaat naar links')
            time.sleep(2.5)
            print('je blijft lopen en lopen, maar je komt niks tegen.')
            time.sleep(5)
            print('je begint de hoop op te geven...')
            time.sleep(5)
            print('je word wakker in een ziekenhuis in een stad!')
            time.sleep(2.5)
            print('iemand had je aan de zijkant van de weg gevonden en meegenomen naar het ziekenhuis!')
            time.sleep(4)
            print()
            print('YOU WIN!')
        elif weg == '2':
            time.sleep(1)
            print('je vind een dode egel langs de weg')
            time.sleep(2.5)
            print('ga je de egel begraven?')
            egel = input('ja (1) of nee (2)? ')
            if egel == '1':
                time.sleep(1)
                print('je besluit de egel te begraven, maar de wolf van eerder kwam ineens uit de bosjes')
                time.sleep(2)
                print('je zag hem niet aankomen en hij beet jou in je nek') 
                time.sleep(4)
                print()
                print('YOU DIED')  
            elif egel == '2':
                time.sleep(2)
                print('je laat de egel wegrotten en loopt verder.')
                time.sleep(4)
                print('je blijft lopen en lopen, maar je komt niks tegen.')
                time.sleep(5)
                print('je begint de hoop op te geven...')
                time.sleep(6)
                print()
                print("YOU DIED")

    elif verlatenDorp == '2':
        time.sleep(1.5)
        print('je komt een wolf tegen en je hebt niks om jezelf te verdedigen')
        print()
        time.sleep(4)
        print('YOU DIED')
def path2():
    time.sleep(1.5)
    print('je loopt een tijdje door een bos totdat je ineens een meer tegenkomt.')
    time.sleep(2.5)
    print('je ziet rechts van je een oude boot liggen, wat doe je?')
    time.sleep(2.5)
    meer = input('ga je over het meer varen (1) of om het meer heen? (2) ')
    if meer == '2':
        time.sleep(2.5)
        print('je loopt verder langs het meer en geniet van het mooie uitzicht')
        time.sleep(2.5)
        print('het mooie bos word al gauw bergachtig.')
        time.sleep(2.5)
        print('je komt een ravijn tegen, wat doe je?')
        time.sleep(2.5)
        ravijn = input('klim je omhoog? (1) of loop je er doorheen? (2) ')
        if ravijn == '1':
            time.sleep(2.5)
            print('je kan via de waterval omhoog (1), dat is minder steil maar wel nat. ')
            time.sleep(1)
            print('of je kan via een rotswand (2), die is steiler, maar wel droog. ')
            klimmen = input('wat word het? ')
            if klimmen == '1':
                time.sleep(1)
                print('je gaat langs de waterval omhoog klimmen.')
                time.sleep(2.5)
                print('tewijl je aan het klimmen bent, glij je uit en je valt op je hoofd')
                time.sleep(4)
                print()
                print("YOU DIED")
            elif klimmen == '2':
                time.sleep(1)
                print('je klimt omhoog en je komt zonder problemen boven.')
                time.sleep(2.5)
                print("eenmaal boven zie je in de verte 2 dorpen liggen.")
                time.sleep(2.5)
                dorp = input("naar welk dorp ga je toe? de linker (1) of de rechter? (2) ")
                if dorp == '1':
                    time.sleep(2.5)
                    print()
                    path1()
                elif dorp == '2':
                    time.sleep(2.5)
                    print('je loopt richting het dorp')
                    time.sleep(2.5)
                    print('je komt zonder problemen bij het dorp aan, en je overleeft')
                    time.sleep(4)
                    print()
                    print("YOU WIN!")
        elif ravijn == '2':
            time.sleep(1)
            print("je besluit door het ravijn heen te lopen")
            time.sleep(2.5)
            print("tijdens het lopen hoor je ineens gerommel.")
            time.sleep(2.5)
            print("je kijkt boven je, en je ziet een hoop stenen op je af vallen.")
            time.sleep(4)
            print()
            print("YOU DIED")
    elif meer == '1':
        time.sleep(2.5)
        print('je sleept de boot het water op en je begint met varen.')
        time.sleep(2.5)
        print('eenmaal op het water, zie je iets verderop het meer.')
        time.sleep(2.5)
        monster = input('ga je er op af? (1) of ga je er omheen? (2) ')
        if monster == '1':
            time.sleep(2)
            print('je besluit er op af te gaan.')
            time.sleep(2.5)
            print('eenmaal dichterbij realiseer je je dat het een groot monster is!')
            time.sleep(2.5)
            print("het kleine bootje maakt geen schijn van kans tegen het grote monster...")
            time.sleep(4)
            print()
            print("YOU DIED")
        elif monster == '2':
            time.sleep(2.5)
            print("je besluit om er omheen te varen.")
            time.sleep(2.5)
            print("tijdens dat je er omheen vaart, let je niet op. vervolgens vaar je over een scherpe steen en je boot begint te zinken")
            time.sleep(2.5)
            print("het water is erg koud.")
            time.sleep(2.5)
            print("eenmaal uit het water, is het veelste koud, en er is een grote kans op onderkoeling...")
            time.sleep(4)
            print()
            print("YOU DIED")
    
loop = True
while loop == True:
    print()
    time.sleep(2.5)
    print('-------------------------------------------------------------------------')
    print('Hallo, u staat op het punt om met mijn spel "gestrand" te starten.')
    print('In dit spel moet je beantwoorden met een cijfer.')
    print("Druk op enter om te starten!")
    input('-------------------------------------------------------------------------')
    print()
    time.sleep(2.5)
    print("je bent gestrand midden in een bos, en jouw doel is om de beschaving te vinden. Succes!")
    time.sleep(2.5)
    print('Je komt een t-splitsing tegen en je kan 2 kanten op, welke kant kies je?')
    tSplitsing = input('links (1) of rechts (2)? ')
    if tSplitsing == '1':
        path1() 
    elif tSplitsing == '2':
        path2()